### PR TITLE
Cycle through pastelist instead of displaying error messages

### PR DESCRIPTION
**Pull request by Arkham**
Hi there!

Thanks for building this plugin, it's really nice to use! One thing that I found was lacking is the ability to cycle through all the entries in the pastelist and loop back to the other end of it, so I've added the functionality.

I'm not sure if you wanted to add a configuration option to enable this behaviour, let me know :)

### CODE REVIEW

**Comment by bfredl** [comment]
Not sure the usefulness of this, the idea is that one just goes through the candidates once until one finds the right one, and use cycle back when one is too quick on the fingers. What is the usecase of literally looping from the end back to the beginning? And won't this usecase be better server by some menu, like the already included denite integration?

**Comment by Arkham** [comment]
I guess that the original idea of kill-ring comes from the fact that it behaves like a ring, so if you're at the start and you try to go back it loops like a ring. Other vim plugins that implement a similar functionality (like [YankRing](https://github.com/vim-scripts/YankRing.vim/blob/master/plugin/yankring.vim#L1209-L1240) and [vim-yankstack](https://github.com/maxbrunsfeld/vim-yankstack/blob/master/autoload/yankstack.vim#L73-L89)) behave in the same way, so I've expected this plugin to behave in the same way.

My best use case is when I am juggling around multiple pastes and I know that I need one of the older pastes I've made, so I just paste and loop back to traverse the list in the opposite direction.

**Comment by bfredl** [comment]
> My best use case is when I am juggling around multiple pastes and I know that I need one of the older pastes I've made, so I just paste and loop back to traverse the list in the opposite direction.

That could be useful, we probably want a clear message when wrapping around though, so that one knows when all items has been processed.

**Comment by Arkham** [comment]
Closing this as I switched away from miniyank, thanks anyway!

**Pull request closed without merging**
